language: python
addons:
  firefox: latest
cache:
  pip: true
  ccache: true
  directories:
    - emsdk/emsdk
python:
  - '3.6'
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xvf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - cd $TRAVIS_BUILD_DIR/emsdk; wget https://github.com/iodide-project/pyodide-demo/raw/toolchain/pyodide_toolchain.tgz; tar -xvf pyodide_toolchain.tgz; cd $TRAVIS_BUILD_DIR
install:
  - pip install pytest selenium
script:
  - make test
