package:
  name: pandas
  version: 0.23.3

source:
  url: https://files.pythonhosted.org/packages/3e/56/82c4d4c049294f87ebd05b65fdcbc9ed68bd23fb0a7e4469caf9a75d199f/pandas-0.23.3.tar.gz
  sha256: 9cd3614b4e31a0889388ff1bd19ae857ad52658b33f776065793c293a29cf612

  patches:
    - patches/avoid-mmap.patch

build:
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
