package:
  name: six
  version: 1.11.0

source:
  url: https://pypi.io/packages/source/s/six/six-1.11.0.tar.gz
  sha256: 70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9


test:
  imports:
    - six
