package:
  name: numpy
  version: 1.14.5

source:
  url: https://files.pythonhosted.org/packages/d5/6e/f00492653d0fdf6497a181a1c1d46bbea5a2383e7faf4c8ca6d6f3d2581d/numpy-1.14.5.zip
  sha256: a4a433b3a264dbc9aa9c7c241e87c0358a503ea6394f8737df1683c7c9a102ac

  patches:
    - patches/add-emscripten-cpu.patch
    - patches/disable-maybe-uninitialized.patch
    - patches/dont-include-execinfo.patch
    - patches/fix-enums.patch
    - patches/fix-longdouble.patch
    - patches/fix-static-init-of-nditer-pywrap.patch
    - patches/force_malloc.patch
    - patches/init-alloc-cache.patch
    - patches/pass-along-errors-from-init.patch
    - patches/use-dummy-threading.patch
    - patches/use-local-blas-lapack.patch
    - patches/fix-install-with-skip-build.patch

build:
  cflags: -include math.h -I../../config


test:
  imports:
    - numpy
